
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller
subjects:
- kind: ServiceAccount
  name: controller

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: controller
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccount: controller
      containers:
      - image: controller:latest
        imagePullPolicy: IfNotPresent
        name: controller
        args: ["--watch-namespace", "$(NAMESPACE)"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 1

---
